git_ssh_key = "/YOUR/SSH/SECRETKEY"

[project.geth_stable]
url = "https://github.com/hhatto/tamatebako"
source = { git = "https://github.com/hhatto/tamatebako.git", branch = "master" }
version_regex = "tag: (v[0-9]+.[0-9]+.[0-9]+(-[a-z][a-z][0-9]+)?)"
